/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.cabinvoicegenerator;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
